version: "3.5"
volumes:
  node-ipc:
  node-db:
services:
  cardano-node:
    image: robertinoiog/cardano-node:1.35.5-v3
    environment:
      NETWORK: ${NETWORK:-preview}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  contracts:
    image: robertinoiog/plutus-pioneer-program-4:v6
    environment:
      NETWORK: ${NETWORK:-preview}
    volumes:
      - ..:/workspace
      - node-ipc:/root/.cardano/preview/
    command: >
      bash -c "
      until /root/.cargo/bin/deno run -A /workspace/CardanoChain-Poultry-Tracker-NFT/src/CardanoChain-Poultry-Tracker/lucid-api.ts; do
        echo 'Waiting for deno to be available...';
        sleep 2;
      done || while sleep 1000; do :; done"
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
